### ISSUE TITLE
How to "run FTSERVER from TCL"?

### ISSUE THREAD

**Issue by elenderg** [ianharper/AccuTermClient#35]
How do I find TCL in Accuterm 7.1? Please provide screenshots.

**Comment by ianharper** [comment]
TCL is not part of Accuterm. It is the name of the shell for D3, maybe other MV databases as well. Jbase calles it Jshell or JQL.

What are you trying to do?

Dec 10, 2022 6:50:55 AM Elender ***@***.***>:

**Comment by elenderg** [comment]
I was trying to create a VB script to copy data from a spreadsheet and paste it into the fields of the current session. The problem is that I am not a MultiValue user.

**Comment by ianharper** [comment]
Ah, you are using the wrong tool. Accuterm Clint is specifically designed as a client for Sublime to manipulate source code on the MV host.

What you are describing, data transfer to/from an MV db and Excel, is a feature of Accuterm. You'll need to either run MV commands or write an MV program to make it work.

Check out the documentation for Accuterm. The info you need is down at the bottom. I can't remember the exact commands off the top of my head.

Dec 10, 2022 9:16:15 AM Elender ***@***.***>:

**Comment by elenderg** [comment]
Thank you very much.

**Comment by ianharper** [comment]
Happy to help! If you need more pointers with AT shoot me a DM.

Dec 10, 2022 10:15:23 AM Elender ***@***.***>:
